#!/usr/bin/env bash
# Displays the contents of the current directory in list format.
#   Only displays the part of the name after the first dash. 

lists=$(ls)
for x in $lists; do
  echo "$x" | cut -d '-' -f2
done