#!/usr/bin/env bash
# Changes Ubuntu server destination
# Change your Local host to 127.0.0.1
# change Facebook IP to 8.8.8.8

cp /etc/hosts ~/hosts.new
echo "127.0.0.1	localhost" > ~/hosts.new
echo "8.8.8.8	facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
